name = "the-jimbo77com-nxt"
main = ".open-next/worker.js"
compatibility_date = "2026-02-10"
compatibility_flags = ["nodejs_compat"]

[vars]
# Admin panel password
ADMIN_KEY = "Haos1977"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[[r2_buckets]]
binding = "MY_R2"
bucket_name = "jimbo77com-assets"
preview_bucket_name = "jimbo77com-assets"
